name: Greet
on: push

jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello Dosto"

  repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Show repository name
        run: echo "The repository name is ${{ github.event.repository.name }}"
  
